title: Central Park.Guide
description: "Your everyday guide to the park that never sleeps."
url: "https://centralpark.guide"
baseurl: ""

permalink: pretty
future: true

collections:
  events:
    output: true
    permalink: /events/:slug/
  personas:
    output: true
    permalink: /personas/:slug/

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: events
    values:
      layout: event
  - scope:
      path: ""
      type: personas
    values:
      layout: persona

plugins:
  - jekyll-seo-tag
